command.help.0=&8&m-------------&8[&4&lHelp&r&8]&8&m-------------
command.help.1=
command.help.2=&8[&4*&8]&7 Click &4&l&nme&r&7 for a list of &4rules&7!
command.help.3=&8[&c*&8]&7 Click &c&l&nme&r&7 to &ccontact &7a&c staff &7member!
command.help.4=&8[&6*&8]&7 Click &6&l&nme&r&7 for the &6links&7 to our socials/Discord!
command.help.5=&8[&e*&8]&7 Click &e&l&nme&r&7 for a list of &ecommands&7!
command.help.6=&8[&a*&8]&7 Click &a&l&nme&r&7 for server &ainformation&7!
command.help.7=&8[&2*&8]&7 Click &2&l&nme&r&7 for a &2reason not listed&7!
command.help.8=&8&m--------------------------------&r

command.help.commands.page.1.0=&8&m-------------&r&8[&e&lCommands&r&8]&8&m-------------
command.help.commands.page.1.1=&8- &e/help &7- access the help menu.
command.help.commands.page.1.2=&8- &e/helpop &7- talk to an online staff member.
command.help.commands.page.1.3=&8- &e/hub &7- return to the hub.
command.help.commands.page.1.4=&8- &e/lobby &7- return to the course lobby.
command.help.commands.page.1.5=&8- &e/join <course name> &7- join a course.
command.help.commands.page.1.6=&8- &e/joinplayer <name> &7- join the course someone is playing.
command.help.commands.page.1.7=&8&m*--&r&8[&7Page &e1 &7of &e2&8]&8&m--*
command.help.commands.page.1.8=&8&m------------------------------------

command.help.commands.page.2.0=&8&m-------------&r&8[&e&lCommands&r&8]&8&m-------------,
command.help.commands.page.2.1=&8- &e/gethotbar &7- restore hotbar.
command.help.commands.page.2.2=&8- &e/leaderboard &7- view the leaderboard for a course.
command.help.commands.page.2.3=&8- &e/myrank &7- join your rank.
command.help.commands.page.2.4=&8- &e/nv &7- toggle night vision.
command.help.commands.page.2.5=&8- &e/playing <name> &7- see which course someone is playing.
command.help.commands.page.2.6=&8- &e/practice &7- toggle practice mode.
command.help.commands.page.2.7=&8&m*--&r&8[&7Page &e2 &7of &e2&8]&8&m--*
command.help.commands.page.2.8=&8&m------------------------------------

command.help.staff.0=&8&m----------&r&8[&{0}&lContact a Staff&r&8]&8&m----------
command.help.staff.1=&8- &7Use &{0}/helpop&7 to contact an online staff!
command.help.staff.2=&8-&7 You can also contact staff via &{0}&nDiscord&7!
command.help.staff.3=&8-&7 Please do not &{0}hackusate&7 in public chat!
command.help.staff.4=&8&m-----------------------------------&r

command.help.socials.0=&8&m-------------&r&8[&6&lLinks&r&8]&8&m-------------
command.help.socials.1=&8- &6&nDiscord&7: https://discord.gg/UbgTYYkR86
command.help.socials.2=&8- &6&nYouTube&7: https://tinyurl.com/486fvbx2
command.help.socials.3=&8- &6&nTwitter&7: https://twitter.com/ScovilleNetwork
command.help.socials.4=&8&m--------------------------------&r

command.help.info.0=&8&m----------&r&8[&a&lServer Info&r&8]&8&m----------
command.help.info.1=&8-&7 Click &a&l&nme&r&7 to join the tutorial!
command.help.info.2=&8-&7 Click &a&l&nme&r&7 for a list of staff members!
command.help.info.3=&8&m--------------------------------&r

command.help.list.0=&8&m----------&r&8[&a&lServer Staff&r&8]&8&m----------
command.help.list.1=&8-&a Owner&7: {0}
command.help.list.2=&8-&a Administrators&7: {1}
command.help.list.3=&8-&a Moderators&7: {2}
command.help.list.4=&8-&a Helpers&7: {3}
command.help.list.5=&8&m--------------------------------&r

command.rules.page.1.0=&8&m*--&r&8[&e&lRules&8]&8&m--*
command.rules.page.1.1=
command.rules.page.1.2=&8[&4#1&8] &7Use common sense.
command.rules.page.1.3=&8[&c#2&8] &7No abusing in-game glitches (locked shulker boxes, leave-join, etc.).
command.rules.page.1.4=&8[&6#3&8] &7No abusing glitches found in the server's plugins.
command.rules.page.1.5=&8[&e#4&8] &7No excessive swearing or sensitive topics.
command.rules.page.1.6=&8[&a#5&8] &7No chat spam or flooding.
command.rules.page.1.7=&8[&2#6&8] &7No toxicity towards other players.
command.rules.page.1.8=
command.rules.page.1.9=&8&m*--&r&8[&7Page &e1 &7of &e2&8]&8&m--*

command.rules.page.2.0=&8&m*--&r&8[&e&lRules&8]&8&m--*
command.rules.page.2.1=
command.rules.page.2.2=&8[&4#7&8] &7The use of any hack is prohibited.
command.rules.page.2.3=&8[&c#8&8] &7The use of macros is prohibited.
command.rules.page.2.4=&8[&6#9&8] &7The use of advantageous mods is prohibited.
command.rules.page.2.5=&8[&e#10&8] &7Helping other players to complete sections, when not intentional, is not allowed.
command.rules.page.2.6=&8[&a#11&8] &7No account sharing.
command.rules.page.2.7=&8[&2#12&8] &7Do not abuse any loopholes found in the rules.
command.rules.page.2.8=
command.rules.page.2.9=&8&m*--&r&8[&7Page &e2 &7of &e2&8]&8&m--*

command.playing.course=&8[&a*&8] &a{0} &7is currently playing {1}&7!
command.playing.nothing=&8[&c*&8] &c{0} &7is not playing a course!
command.playing.usage=&8[&c*&8] &cUsage&7: /playing &cusername

command.tag.usage=&8[&c*&8] &cUsage&7: /tag set ...

command.tag.set.usage=&8[&c*&8] &cUsage&7: /tag set &ctag_id (or "tag id") type tag